# Generated by Django 4.2.7 on 2023-11-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='волейбол игра', max_length=50)),
                ('game_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('NA', 'Not_active')], default='AC', max_length=2)),
            ],
            options={
                'ordering': ['-game_date'],
            },
        ),
    ]
