# Generated by Django 4.2.7 on 2023-11-07 08:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
