# Generated by Django 4.2.7 on 2023-11-13 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volleyball', '0006_alter_game_players_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='adress',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
